# \u8CC7\u6599\u5EAB\u9023\u7DDA\u8A2D\u5B9A (\u8ACB\u8A18\u5F97\u5148\u53BB MySQL \u5EFA\u7ACB\u4E00\u500B\u540D\u70BA thestar_db \u7684\u8CC7\u6599\u5EAB)
spring.datasource.url=jdbc:mysql://localhost:3306/restaurant?serverTimezone=Asia/Taipei&characterEncoding=utf-8
spring.datasource.username=root
spring.datasource.password=123456

# JPA \u81EA\u52D5\u5EFA\u7ACB\u8207\u66F4\u65B0\u8CC7\u6599\u8868\u8A2D\u5B9A
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true